// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Bytes$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Bytes",
  "sourceName": "@openzeppelin/contracts/utils/Bytes.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220bca8f12d599213b324dd67470aaeb19603b0ee9d4e982ec8ebe8d4b7bea286dd64736f6c63430008180033",
  "deployedBytecode": "0x5f80fdfea2646970667358221220bca8f12d599213b324dd67470aaeb19603b0ee9d4e982ec8ebe8d4b7bea286dd64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Bytes",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Bytes.sol:Bytes",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Bytes",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Bytes$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Bytes.sol:Bytes",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Bytes$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Bytes",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Bytes.sol:Bytes",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Bytes$Type["abi"]>>;
}
