// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignedMath$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SignedMath",
  "sourceName": "@openzeppelin/contracts/utils/math/SignedMath.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212202c28011710a5ff1d3e421d6c7f474166ecb6290547a4e65b0208041f3ba7dd7c64736f6c63430008180033",
  "deployedBytecode": "0x5f80fdfea26469706673582212202c28011710a5ff1d3e421d6c7f474166ecb6290547a4e65b0208041f3ba7dd7c64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignedMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/math/SignedMath.sol:SignedMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignedMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignedMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/math/SignedMath.sol:SignedMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignedMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignedMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/math/SignedMath.sol:SignedMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;
}
