// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ERC721Utils$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ERC721Utils",
  "sourceName": "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol",
  "abi": [],
  "bytecode": "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122005667503b4120855ef88c7a16bdb78387c0baf7ef70663fc107f1e49d2da471364736f6c63430008180033",
  "deployedBytecode": "0x5f80fdfea264697066735822122005667503b4120855ef88c7a16bdb78387c0baf7ef70663fc107f1e49d2da471364736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ERC721Utils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ERC721Utils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC721Utils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ERC721Utils$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ERC721Utils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/token/ERC721/utils/ERC721Utils.sol:ERC721Utils",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ERC721Utils$Type["abi"]>>;
}
