// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BaseReputationSBT$Type } from "./BaseReputationSBT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BaseReputationSBT"]: BaseReputationSBT$Type;
    ["contracts/BaseReputationSBT.sol:BaseReputationSBT"]: BaseReputationSBT$Type;
  }

  interface ContractTypesMap {
    ["BaseReputationSBT"]: GetContractReturnType<BaseReputationSBT$Type["abi"]>;
    ["contracts/BaseReputationSBT.sol:BaseReputationSBT"]: GetContractReturnType<BaseReputationSBT$Type["abi"]>;
  }
}
